version: "2.0"
services:
  openqa-trigger:
    build:
      dockerfile: Dockerfile
      context: openqa-trigger
    restart: always
    environment:
      - RUN_EVERY=600
    volumes:
      - .:/home/frontend/openqa-trigger
  openqa-mail-notification:
    build:
      dockerfile: Dockerfile
      context: openqa-mail-notification
    restart: always
    environment:
      - RUN_EVERY=600
    volumes:
      - .:/home/frontend/openqa-mail-notification
  obs-package-status:
    build:
      dockerfile: Dockerfile
      context: obs-package-status
    restart: always
    environment:
      - RUN_EVERY=600
    volumes:
      - .:/home/frontend/obs-package-status
