version: "2.0"
services:
  openqa-mail-notification:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      - RUN_EVERY=600
    volumes:
      - .:/home/frontend/openqa-mail-notification
